name: Build and Release (Draft)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build, Test and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

  build-app:
      strategy:
        fail-fast: false

        matrix:
          os: [ windows-latest, ubuntu-latest, macos-latest ]
          include:
            - os: windows-latest
              script: "build:win"
            - os: ubuntu-latest
              script: "build:linux"
            - os: macos-latest
              script: "build:mac"

      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4

        - name: setup node
          uses: actions/setup-node@v4
          with:
            node-version: 22

        - name: Setup
          run: npm ci

        - name: Tooling (Linux)
          if: matrix.os == 'ubuntu-latest'
          run: |
            sudo apt update
            sudo apt install snapd
            sudo snap install --classic snapcraft

        - name: Tooling (Win)
          if: matrix.os == 'windows-latest'
          run: |
            npm install -g win-node-env

        - name: Test
          run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless
          continue-on-error: true

        - name: Setup macOS Certificate
          if: matrix.os == 'macos-latest'
          uses: apple-actions/import-codesign-certs@v1
          with:
            p12-file-base64: ${{ secrets.APPLE_CERT_P12 }}
            p12-password: ${{ secrets.APPLE_CERT_P12_PASSWORD }}
            team-id: ${{ secrets.APPLE_TEAM_ID }}

        - name: Build and Publish
          run: npm run ${{matrix.script}}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
            APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
            CSC_LINK: ${{ secrets.APPLE_CERT_P12 }}
            CSC_KEY_PASSWORD: ${{ secrets.APPLE_CERT_P12_PASSWORD }}
            CSC_NAME: ${{ secrets.APPLE_DEVELOPER_ID }}

        - name: Notarize macOS App
          if: matrix.os == 'macos-latest'
          run: |
            # Find the .app file
            APP_PATH=$(find dist -name "*.app" -type d)
            
            # Create a temporary zip file for notarization
            ditto -c -k --keepParent "$APP_PATH" "app.zip"
            
            # Submit for notarization
            xcrun notarytool submit "app.zip" \
              --apple-id "${{ secrets.APPLE_DEVELOPER_ID }}" \
              --password "${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}" \
              --team-id "${{ secrets.APPLE_TEAM_ID }}" \
              --wait
            
            # Staple the notarization ticket
            xcrun stapler staple "$APP_PATH"
            
            # Clean up
            rm app.zip